<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="width" value="0.2" />
  <xacro:property name="leglen" value="0.6" />
  <xacro:property name="legwidth" value="0.1" />
  <xacro:property name="legheight" value="0.2" />
  <xacro:property name="wheeldiam" value="0.2" />

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3" />
    </inertial>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
      <material name="red"/>
    </collision>
    <xacro:default_inertial mass="20"/>
  </link>

  <xacro:macro name="wheel" params="prefix">

    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.1"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.1"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="1"/>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="${prefix}_leg"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="-${leglen/3} 0 -${legheight/2}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>
  <xacro:macro name="leg" params="prefix reflect">
    <link name="${prefix}_leg">
      <visual>
        <geometry>
          <box size="${leglen} ${legwidth} ${legheight}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${leglen} ${legwidth} ${legheight}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="base_to_${prefix}_leg" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_leg"/>
      <origin xyz="${leglen/3} ${reflect*(width+legwidth/2)} -${width/2}" />
    </joint>
    <xacro:wheel prefix="${prefix}" />
  </xacro:macro>
  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />

  <link name="caster_base">
    <visual>
      <geometry>
        <box size="${2*width} ${legheight/2} ${legwidth}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="${2*width} ${legheight/2} ${legwidth}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
      <material name="red"/>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>
  <joint name="base_to_caster_base" type="fixed">
    <parent link="base_link"/>
    <child link="caster_base"/>
    <origin xyz="${2*leglen/3} 0 -${width/2}" rpy="0 0 0"/>
  </joint>

  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${wheeldiam/2}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheeldiam/2}"/>
      </geometry>
      <material name="black"/>
    </collision>
    <xacro:default_inertial mass="2"/>
  </link>
  <joint name="caster_wheel_to_caster_base" type="fixed">
    <parent link="caster_base"/>
    <child link="caster_wheel"/>
    <origin xyz="0 0 -${legheight/2}" rpy="0 0 0"/>
  </joint>
  <link name="antenna">
    <visual>
        <origin xyz="0 0 ${width}" rpy="0 0 0" />
        <geometry>
            <cylinder length="${width*2}" radius="${width/8}" />
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <origin xyz="0 0 ${width}" rpy="0 0 0" />
        <geometry>
            <cylinder length="${width*2}" radius="${width/8}" />
        </geometry>
        <material name="blue"/>
    </collision>
    <xacro:default_inertial mass="5"/>
  </link>
  <joint name="antenna_to_base" type="prismatic">
    <parent link="base_link"/>
    <child link="antenna"/>
    <origin xyz="0 0 -${width}" rpy="0 0 0"/>
    <limit effort="1000.0" lower="0" upper="${width*2}" velocity="0.5"/>
    <axis xyz="0 0 1"/>
  </joint>
  <link name="antenna_plate">
    <visual>
            <geometry>
                <cylinder length="${width/8}" radius="${width/2}" />
            </geometry>
            <material name="blue"/>
    </visual>
    <collision>
            <geometry>
                <cylinder length="${width/8}" radius="${width/2}" />
            </geometry>
            <material name="blue"/>
    </collision>
    <xacro:default_inertial mass="2"/>
  </link>
  <joint name="antenna_plate_joint" type="continuous">
    <parent link="antenna"/>
    <child link="antenna_plate"/>
    <origin xyz="0 0 ${width*2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
  <xacro:macro name="antenna_horn" params="prefix reflect">
    <link name="${prefix}_horn">
        <visual>
                <geometry>
                    <cylinder length="${width}" radius="${width/10}" />
                </geometry>
                <material name="blue"/>
        </visual>
        <collision>
                <geometry>
                    <cylinder length="${width}" radius="${width/10}" />
                </geometry>
                <material name="blue"/>
        </collision>
        <xacro:default_inertial mass="2"/>
    </link>
    <joint name="${prefix}_horn_to_antenna_plate" type="fixed">
        <parent link="antenna_plate"/>
        <child link="${prefix}_horn"/>
        <origin xyz="0 ${reflect*width/4} ${width/2}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  <xacro:antenna_horn prefix="right" reflect="-1" />
  <xacro:antenna_horn prefix="left" reflect="1" />
</robot>